#!/bin/bash
CONFIGFILE=/etc/default/debmatic

. /usr/share/debconf/confmodule

set -e

case "$1" in
  configure|abort-upgrade)
    udevadm control --reload-rules && udevadm trigger

    if [ ! -e /usr/sbin/debmatic-info ]; then
      ln -s /usr/share/debmatic/bin/debmatic-info.sh /usr/sbin/debmatic-info
    fi
    if [ ! -e /usr/sbin/debmatic-backup ]; then
      ln -s /usr/share/debmatic/bin/debmatic-backup.sh /usr/sbin/debmatic-backup
    fi

    cp /usr/share/debmatic/VERSION /boot/VERSION

    systemctl daemon-reload

    for service in `ls /lib/systemd/system/debmatic*.service | xargs -n 1 basename`
    do
      if [ ! -e /lib/systemd/system/"${service%.service}.timer" ]; then
        systemctl enable $service
      fi
    done
    for timer in `ls /lib/systemd/system/debmatic*.timer | xargs -n 1 basename`
    do
      systemctl enable $timer
    done

    lighttpd-enable-mod debmatic
    systemctl force-reload lighttpd.service

    if [ -d /usr/share/debmatic/hooks/postinst ]; then
      run-parts /usr/share/debmatic/hooks/postinst
    fi

    systemctl start debmatic.service
    ;;

  reconfigure|abort-remove|abort-deconfigure)
    ;;

esac

