#!/bin/bash
. /usr/share/debconf/confmodule

set -e

case "$1" in
  purge)
    db_purge
    rm -f /etc/default/debmatic
    rm -rf /etc/config
    rm -rf /etc/config_templates
    ;;

  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
esac

