#!/bin/bash

set -e

case "$1" in
  remove|upgrade|deconfigure)
    /usr/local/addons/cuxd/update_addon cuxd
    rm -f /usr/local/etc/config/addons/www/cuxd
    systemctl disable cuxd.service
    systemctl restart debmatic.service
    ;;

  failed-upgrade)
    ;;
esac
