#!/bin/bash

set -e

ADDON_NAME=jp-hb-devices-addon

ADDON_DIR=/usr/local/addons/${ADDON_NAME}
PATCH_DIR=${ADDON_DIR}/patch
WWW_DIR=/etc/config/addons/www/${ADDON_NAME}
LOG_DIR=${ADDON_DIR}/log
GLOBAL_LOGFILE=$LOG_DIR/inst.log
GLOBAL_ERRFILE=$LOG_DIR/inst.err
PATCH_REVOKE_ERRFILE=$ADDON_DIR/log/revoke.err
FIRMWARE_DIR=/firmware/rftypes
CUSTOMIZED_FIRMWARE_DIR=${ADDON_DIR}/customized_firmware
RC_DIR=/usr/local/etc/config/rc.d
CK_FIRMWARE_FILE=${FIRMWARE_DIR}/hb-uni-sen-cap-moist.xml

case "$1" in
  remove|upgrade|deconfigure)
    cd /usr/local/addons/jp-hb-devices-addon
    for f in /usr/local/addons/jp-hb-devices-addon/uninstall_* ; do echo "  - $(basename $f)"; ./$(basename $f); done
      
    cd /www

    patchsubdir=common
    for patchfile in ${PATCH_DIR}/$patchsubdir/* ; do
      echo "Rejecting $patchsubdir patch file $(basename $patchfile)" | tee -a $GLOBAL_LOGFILE
      patch --dry-run -R -s -f -p3 -i $patchfile && patch -R -p3 -i $patchfile
    done

    patchsubdir=le_343
    for patchfile in ${PATCH_DIR}/$patchsubdir/* ; do
      echo "Rejecting $patchsubdir patch file $(basename $patchfile)" | tee -a $GLOBAL_LOGFILE
      patch --dry-run -R -s -f -p3 -i $patchfile && patch -R -p3 -i $patchfile
    done

    patchsubdir=ge_345
    for patchfile in ${PATCH_DIR}/$patchsubdir/* ; do
      echo "Rejecting $patchsubdir patch file $(basename $patchfile)" | tee -a $GLOBAL_LOGFILE
      patch --dry-run -R -s -f -p3 -i $patchfile && patch -R -p3 -i $patchfile
    done

    [[ -f ./webui/webui.js.orig ]] && rm ./webui/webui.js.orig
    [[ -f ./rega/esp/datapointconfigurator.fn.orig ]] && rm ./rega/esp/datapointconfigurator.fn.orig
    [[ -f ./rega/esp/functions.fn.orig ]] && rm ./rega/esp/functions.fn.orig
    [[ -f ./rega/esp/side.inc.orig ]] && rm ./rega/esp/side.inc.orig
    [[ -f ./rega/pages/tabs/admin/views/programs.htm.orig ]] && rm ./rega/pages/tabs/admin/views/programs.htm.orig
    [[ -f ./config/ic_common.tcl.orig ]] && rm ./config/ic_common.tcl.orig
    [[ -f ./webui/js/extern/jp_webui_inc.js ]] && rm ./webui/js/extern/jp_webui_inc.js

    systemctl disable jp-hb-devices.service
    systemctl restart debmatic.service
    ;;

  failed-upgrade)
    ;;
esac
