#!/bin/bash
set -e

. /usr/share/debconf/confmodule

case "$1" in
  purge)
    db_purge
    rm -rf /usr/share/cloudmatic
    ;;

  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;
esac

